### PR TITLE
Fix list_cameras error in windows

### PR DESCRIPTION
**Pull request by Diamantino-Op**

### CODE REVIEW

**Comment by Diamantino-Op** [comment]
wait, why did it add the other files too, just apply the edits of list_cameras

**Review by ghost — APPROVED** [review]

**Comment by Diamantino-Op** [comment]
@thevickypedia i reverted the changes i made locally and left only the fix for the list_cameras.

**Comment by thevickypedia** [comment]
@Diamantino-Op Good catch on the buggy condition. Can you please update the release notes in the existing format.

**Comment by Diamantino-Op** [comment]
@thevickypedia do i have to create a new version like 7.5.7 or update the 7.5.6?

**Comment by Diamantino-Op** [comment]
@thevickypedia updated

**Pull request merged**
