### PR TITLE
Some cool, small features 

### PR DESCRIPTION
**Pull request by ariv797**
Jarvis can now play heads-or-tails, tell you an inspirational quote, tell you a fun fact and click screenshots

### CODE REVIEW

**Comment by ariv797** [comment]
Sorry for having so many commits I made a mistake as this is my first time contributing to Github

**Comment by ariv797** [comment]
pls ignore this commit

**Review by thevickypedia — COMMENTED** [review]
Did you check wikiquotes before adding it? Because it will not work the way you have provided, as it requires [2 parameters](https://github.com/FranDepascuali/wikiquotes-python-api/blob/master/wikiquotes/wikiquotes_api.py#L68-L75) and I'm skeptical about asking Jarvis to include the Author name as there is a lot involved to extract author name from a phrase.

**Comment by thevickypedia** [comment]
The wikiquotes did not work the way we'd regularly use so skipping it. Great thoughts about the heads or tails and random facts.

https://github.com/thevickypedia/Jarvis/commit/435815a657550ed7b9cbc124c28c004d9ad4f98e

**Pull request closed without merging**
